# Generated by Django 4.1.1 on 2022-10-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo", old_name="timetamp", new_name="timestamp",
        ),
    ]
