# Generated by Django 4.1.1 on 2022-09-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asigm_1_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(auto_created=True),
        ),
    ]
