# Generated by Django 4.1.1 on 2022-09-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_person"),
    ]

    operations = [
        migrations.DeleteModel(name="Person",),
    ]
