# Generated by Django 4.1.1 on 2022-10-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_group_person_membership_group_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(model_name="membership", name="group",),
        migrations.RemoveField(model_name="membership", name="person",),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "commoninfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.commoninfo",
                    ),
                ),
                ("home_group", models.CharField(max_length=5)),
            ],
            bases=("polls.commoninfo",),
        ),
        migrations.DeleteModel(name="Group",),
        migrations.DeleteModel(name="Membership",),
        migrations.DeleteModel(name="Person",),
    ]
