# Generated by Django 4.1.1 on 2022-10-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0008_persona_mypersona"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderedPerson",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="polls.person",
                    ),
                ),
            ],
            bases=("polls.person",),
        ),
    ]
