# Generated by Django 4.1.1 on 2022-10-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0009_orderedperson"),
    ]

    operations = [
        migrations.RemoveField(model_name="group", name="members",),
        migrations.RemoveField(model_name="membership", name="group",),
        migrations.RemoveField(model_name="membership", name="person",),
        migrations.RemoveField(model_name="orderedperson", name="person_ptr",),
        migrations.DeleteModel(name="Persona",),
        migrations.RemoveField(model_name="restaurant", name="place_ptr",),
        migrations.RemoveField(model_name="student", name="commoninfo_ptr",),
        migrations.DeleteModel(name="MyPersona",),
        migrations.DeleteModel(name="CommonInfo",),
        migrations.DeleteModel(name="Group",),
        migrations.DeleteModel(name="Membership",),
        migrations.DeleteModel(name="OrderedPerson",),
        migrations.DeleteModel(name="Person",),
        migrations.DeleteModel(name="Place",),
        migrations.DeleteModel(name="Restaurant",),
        migrations.DeleteModel(name="Student",),
    ]
