# Generated by Django 4.1.1 on 2022-10-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0010_remove_group_members_remove_membership_group_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tagline", models.TextField()),
            ],
        ),
    ]
