# Generated by Django 4.1.1 on 2022-10-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
