# Generated by Django 4.1.1 on 2022-10-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0015_author_entry"),
    ]

    operations = [
        migrations.RemoveField(model_name="entry", name="authors",),
        migrations.RemoveField(model_name="entry", name="blog",),
        migrations.DeleteModel(name="Author",),
        migrations.DeleteModel(name="Blog",),
        migrations.DeleteModel(name="Entry",),
    ]
