# Generated by Django 4.1.1 on 2022-10-08 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asigm_1_tapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="person",
            name="person_id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="asigm_1_tapp.manufacturer",
                    ),
                ),
            ],
        ),
    ]
