# Generated by Django 4.1.1 on 2022-10-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asigm_1_tapp", "0002_manufacturer_alter_person_person_id_car"),
    ]

    operations = [
        migrations.RenameField(model_name="car", old_name="name", new_name="name_car",),
        migrations.AlterField(
            model_name="car",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
