# Generated by Django 4.1.1 on 2022-10-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asigm_1_tapp", "0003_rename_name_car_name_car_alter_car_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
