# Generated by Django 4.1.1 on 2022-10-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asigm_1_tapp", "0004_alter_manufacturer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
